//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VENTAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int id_empleado { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public string nombre_empleado { get; set; }
        public string apellido_empleado { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
    
        public virtual Cargo Cargo { get; set; }
    }
}
